// Hardcoded sample data since no backend
export const sampleProducts = [
  {
    _id: "1",
    slug: "example-script",
    name: "Example Code",
    images: [
      "https://images.pexels.com/photos/45980/pexels-photo-45980.jpeg",
      "https://images.pexels.com/photos/5661241/pexels-photo-5661241.jpeg",
      "https://images.pexels.com/photos/30399211/pexels-photo-30399211.jpeg",
      "https://images.pexels.com/photos/5833316/pexels-photo-5833316.jpeg",
    ],
    codeLanguages: ["Python", "JavaScript", "Node.js"],
    codeLink: "https://github.com",
    codePreview: "https://anasmalikportfolio.vercel.app",
    previousLink: "https://anasmalikportfolio.vercel.app/",
    clientSideRequirements: "Modern browser, Node.js v18+, Internet connection",
    installationType: ["Web", "Android"],
    basePrice: 1500,
    additionalCharges: {
      installation: 500,
      customization: 2000,
      branding: 1000,
      paymentGatewayIntegration: 1500,
      deployment: 800,
      cloudSetup: 1200,
      playConsoleUpload: 300,
      iosConsoleUpload: 400,
    },
    description: "A versatile script for automation tasks.",
    category: "Automation",
  },
  {
    _id: "2",
    slug: "another-script",
    name: "Another Code",
    images: ["https://images.pexels.com/photos/1370296/pexels-photo-1370296.jpeg", "https://images.pexels.com/photos/1454360/pexels-photo-1454360.jpeg", "https://images.pexels.com/photos/3184328/pexels-photo-3184328.jpeg"],
    codeLanguages: ["Java", "Kotlin"],
    codeLink: "https://github.com/",
    codePreview: "https://anasmalikportfolio.vercel.app/",
    previousLink: "https://anasmalikportfolio.vercel.app/",
    clientSideRequirements: "Android SDK, Java 17+",
    installationType: ["Android", "iOS"],
    basePrice: 2500,
    additionalCharges: {
      installation: 700,
      customization: 3000,
      branding: 1500,
      paymentGatewayIntegration: 2000,
      deployment: 1000,
      cloudSetup: 1500,
      playConsoleUpload: 500,
      iosConsoleUpload: 600,
    },
    description: "Mobile app script for e-commerce.",
    category: "E-commerce",
  },
  // Add more samples if needed
];
